/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("cards").insert([
    {
      user_id: 1,
      category_id: "1",
      front_text: "What do you call a pony with a cough?",
      back_text: "A little horse",
      views: 0,
      flag_report:false,
    },
    {
      category_id: "1",
      user_id: 2,
      front_text: "What did one hat say to the other?",
      back_text: "You wait here. I'll go on a head.",
      views: 0,
      flag_report:false,
    },
    {
      user_id: 3,
      category_id: "1",
      front_text: "What do you call a magic dog?",
      back_text: "A labracadabrador.",
      views: 0,
      flag_report:false,
    },
    {
      user_id: 4,
      category_id: "1",
      front_text: "Why can’t you hear a pterodactyl go to the bathroom?",
      back_text: "Because the “P” is silent.",
      views: 0,
      flag_report:false,
    },
    {
      user_id: 5,
      category_id: "1",
      front_text: "What did the pirate say when he turned 80?",
      back_text: "Aye matey.",
      views: 0,
      flag_report:false,
    },
    {
      user_id: 6,
      category_id: "2",
      front_text: "Who directed the 1994 film 'Pulp Fiction'?",
      back_text: "Quentin Tarantino",
      views: 0,
      flag_report:false,
    },
    {
      user_id: 7,
      category_id: "2",
      front_text: "What is the name of the city 'The Simpsons' is set in?",
      back_text: "Springfield",
      views: 0,
      flag_report:false,
    },
    {
      user_id: 8,
      category_id: "2",
      front_text: "What was Elvis Presley's middle name?",
      back_text: "Aaron",
      views: 0,
      flag_report:false,
    },
    {
      user_id: 9,
      category_id: "2",
      front_text: "Which sport has a penalty shot?",
      back_text: "Soccer/Football",
      views: 0,
      flag_report:false,
    },
    {
      user_id: 10,
      category_id: "2",
      front_text: "Who, as of 2024, currently owns X, formerly Twitter?",
      back_text: "Elon Musk",
      views: 0,
      flag_report:false,
    },
    {
      user_id: 11,
      category_id: "1",
      front_text: "What is forecast?",
      back_text: "It's Condition",
      views: 0,
      flag_report:false,
    },
    {
      user_id: 12,
      category_id: "1",
      front_text: "Life is too short for?",
      back_text: "Browse without dark mode!",
      views: 0,
      flag_report:false,
    },
    {
      user_id: 13,
      category_id: "1",
      front_text: "What is in the back?",
      back_text: "Maybe a test",
      views: 0,
      flag_report:false,
    },
    {
      user_id: 14,
      category_id: "1",
      front_text: "Who is Brandon?",
      back_text: "Spencer",
      views: 0,
      flag_report:false,
    },
    {
      user_id: 15,
      category_id: "1",
      front_text: "Why was the JavaScript developer sad?",
      back_text: "Because they didn't Node how to Express himself",
      views: 0,
      flag_report:false,
    },
    {
      user_id: 16,
      category_id: "1",
      front_text: "Why did the React class component feel relieved?",
      back_text: "Because it was now off the hook.",
      views: 0,
      flag_report:false,
    },
    {
      user_id: 17,
      category_id: "1",
      front_text: "Don't trust JavaScript programmers.",
      back_text: "All they do is promises but they never callback.",
      views: 0,
      flag_report:false,
    },
    {
      user_id: 18,
      category_id: "1",
      front_text: "You want to hear a javascript joke?",
      back_text: "I'll callback later",
      views: 0,
      flag_report:false,
    },
    {
      user_id: 19,
      category_id: "1",
      front_text: "Why you should date a javascript developer?",
      back_text: "Because they always callback.",
      views: 0,
      flag_report:false,
    },
  ]);
};
